### ISSUE TITLE
notify method can not be processed with hash argument

### ISSUE THREAD

**Issue by StanisLove** [palkan/active_delivery#10]
Simple test https://github.com/StanisLove/active_delivery/blob/67461a0623804d08208f576a7e7bb930cc5fb1ab/spec/active_delivery/lines/mailer_spec.rb#L59-L63

The reason for this behavior lies in the https://github.com/palkan/active_delivery/blob/1c05a0353ca98de285a0202d25bc1a6439e43785/lib/active_delivery/base.rb#L102
and key-word `sync:` argument.

I believe that a hash should be correctly processed like any other argument and it needs some refactoring here.

**Comment by palkan** [comment]
> I believe that a hash should be correctly processed like any other argument

Agree.

> and it needs some refactoring here.

Yeah. I think, we should avoid using kwargs and find another way for passing `params` and `sync` options. That would allow us proxying all args to the underlying line.

**Comment by StanisLove** [comment]
https://github.com/palkan/active_delivery/pull/11

**Comment by palkan** [comment]
Added in 0.4.0
