### ISSUE TITLE
RSpec matchers doesn't work

### ISSUE THREAD

**Issue by iBublik** [palkan/active_delivery#12]
When I try to use negated matcher in RSpec, I get the following error:
```
Failure/Error: expect { subject }.to have_not_delivered_to(MyDelivery)
       You must pass an argument rather than a block to use the provided matcher (have not delivered to MyDelivery), or the matcher must implement `supports_block_expectations?`.
```

The reason in method lookup path and matcher's name which leads to this point:
https://github.com/rspec/rspec-expectations/blob/33e3c614f82be81f81e09f8725b6bc450f7c40d0/lib/rspec/matchers.rb#L962-L963

Would love to send PR with fix if you give me a hint :)

**UPDATED**: problem is not only with negated matchers, but with all RSpec matchers

**Comment by iBublik** [comment]
Oh, I found that the actual reason is Spring. Any advices with how to fix that?

**Comment by palkan** [comment]
> Any advices with how to fix that?

The easiest way to fix Spring is to get rid off it))

**Comment by iBublik** [comment]
I understand, but it's not an option for now :)

**Comment by palkan** [comment]
> the actual reason is Spring

Could you tell more about this? Spring shouldn't break anything after restart

**Comment by iBublik** [comment]
After some debugging I found that this check fails https://github.com/palkan/active_delivery/blob/master/lib/active_delivery/testing.rb#L48 and file is not required. Don't know why running via Spring makes `RSpec` constant to be not defined at this moment.
For now I just added `require 'active_delivery/testing/rspec'` in my `rails_helper.rb` and everything works fine. I can make a PR with addition to documentation about this case if it's ok to you

**Comment by palkan** [comment]
> Don't know why running via Spring makes RSpec constant to be not defined at this moment.

Got it.

Do you have `spring-commands-rspec`?_)

We had a similar problem in `test-prof`: https://github.com/palkan/test-prof/issues/8

Solution would be to change the check to `defined?(RSpec::Core)`. Could you check it and propose a PR if it works?

**Comment by iBublik** [comment]
> Do you have `spring-commands-rspec`?_)

Bingo :)

> Solution would be to change the check to `defined?(RSpec::Core)`. Could you check it and propose a PR if it works?

Unfortunately it didn't help

**Comment by palkan** [comment]
Hm, what about adding `require "active_delivery/testing/rspec"` to `rails_helper.rb` explicitly?

**Comment by iBublik** [comment]
> Hm, what about adding `require "active_delivery/testing/rspec"` to `rails_helper.rb` explicitly?

Already done that, see my comment https://github.com/palkan/active_delivery/issues/12#issuecomment-580142662

**Comment by palkan** [comment]
Sorry, missed this.

>  I can make a PR with addition to documentation about this case if it's ok to you

That would be great)

**Comment by brovikov** [comment]
@palkan probably we could in doc explicitly tell to use `require "active_delivery/testing/rspec"` because now it shows `require "active_delivery/testing"` and it doesn't make a trick for me, when spring is using.

**Comment by palkan** [comment]
Done. Thanks!
