### ISSUE TITLE
ActiveDelivery::TestDelivery does not work with fibers

### ISSUE THREAD

**Issue by pauldub** [palkan/active_delivery#17]
The ActiveDelivery::TestDelivery module user fiber-local storage to store its state. This makes its behavior break when using rspec matchers to test a delivery done in a fiber.

## Steps to reproduce

```ruby
class SomeDelivery < ActiveDelivery::Base
end

RSpec.describe SomeDelivery do
  it 'works with fibers' do
    expect do
      Fiber.new { SomeDelivery.notify!(:event) }.resume
    end.to have_delivered_to(SomeDelivery, :event)
  end
end
```

## Actual Behavior

```shell
Failures:

  1) SomeDelivery works with fibers
     Failure/Error:
       expect do
         Fiber.new { SomeDelivery.notify!(:event) }.resume
       end.to have_delivered_to(SomeDelivery, :event)

       expected to deliver :event notification via SomeDelivery with:
        - args: <none>
       exactly once, but haven't delivered anything
     # ./spec/some_delivery.rb:8:in `block (2 levels) in <top (required)>'
```

## Expected behaviour

```shell
Finished in 0.09412 seconds (files took 2.25 seconds to load)
1 example, 0 failures
```

## Comments

This is behavior is related to the usage of `Thread#[]` and `Thread#[]=` to set the `TestModule` internal state which are both fiber-local.

I believe this is not the intended behavior and could be fixed by using `Thread#thread_variable_set` and `Thread#thread_variable_get` methods.

In any case if you think this is worth fixing I can open a pull request for this.

**Comment by palkan** [comment]
Thanks for the report!

I think, for testing purposes using a thread-local storage is OK (haven't heard about any testing framework using fibers for concurrency yet). PR is welcomed!

**Comment by pauldub** [comment]
> haven't heard about any testing framework using fibers for concurrency yet

Neither do I, but I'm using `dry-effects` which wraps an operation delivering notifications in a fiber, so their delivery cannot be tested.
