### ISSUE TITLE
Folders structure

### ISSUE THREAD

**Issue by apuntovanini** [palkan/active_delivery#20]
Hi, how would you suggests folders to be organized for deliveries and lines? something like app/deliveries and app/services/lines?
I know it's completely up to the developer, but I wonder whether you have a pattern to suggest for structuring this better!
Thanks

**Comment by palkan** [comment]
Hey!

I would put deliveries to `app/deliveries`, as you suggest. As for lines, depending on what other application code they depend on, that could be either `app/lib` or `app/services` or even _local_ gems (i.e., `gems/my_line/...`).

**Comment by apuntovanini** [comment]
Thanks @palkan!
