### ISSUE TITLE
"notify_later" on new line is a bit tricky

### ISSUE THREAD

**Issue by benebrice** [palkan/active_delivery#24]
## Is your feature request related to a problem? Please describe.
On new line implementation, I figured out that example given is not working perfectly with parameterized mailer/line

## Describe the solution you'd like

```ruby
# `kwargs.merge(line.params)` is the path I found
def notify_later(line, delivery_action, *args, **kwargs)
  NewLineJob.perform_later line.class, delivery_action, *args, **kwargs.merge(line.params)
end
```

unless this, we cannot handle parametrized value on class method. Here is my second implementation on the new line

```ruby
class NewLine
    attr_reader :params

    class << self
      ##
      # Class method to init (for async) and call the instance method
      def my_method(*args)
        with(args.last).my_method
      end
   end

  def initialize(params = {})
      @params = params
      # Do something else with params
    end
  end
end
```

## Describe alternatives you've considered

I'm not 100% sure this works in all cases. Can you confirm with the whole gem knowledge
@palkan ?
In my case it's not a problem because all my mailers are parameterized (adding tracking headers) but I did not check with non-parameterized method after this fix.

**Comment by palkan** [comment]
`notify_later` doesn't know anything about params: it accepts a _handler_ (which should keep the information about the params). Action Mailer implements this by wrapping a mailer class in a proxy (see, for example, [abstract_notifier](https://github.com/palkan/abstract_notifier/blob/2b154f993b770e554af31f88fab6d0fcfab8080f/lib/abstract_notifier/base.rb#L28-L49)).

In you case, you can try to handle param in `NewLineJob`:

```
def notify_later(line, delivery_action, *args, **kwargs)
  NewLineJob.perform_later line.class.to_s, delivery_action, *args, **kwargs.merge(params: line.params)
end

class NewLineJob
  def perform(klass, action, *args, params: nil, **kwargs)
    handler = params ? klass.with(**params) : klass.new
   
    handler.public_send(action, *args, **kwargs)
  end
end
```

**Comment by benebrice** [comment]
This is better. I made an update on `line.class.to_s` to `line.class` to match common usage. 

Maybe we can upgrade the example to add one with parameterized new line? I think I won't be the only one to have this issue since the gem is becoming popular. 🙂 
What do you think?

**Comment by palkan** [comment]
That's a good idea. Would you like to propose a PR?

**Comment by benebrice** [comment]
Sure! Here it is #25

**Comment by palkan** [comment]
Thank you!
