### ISSUE TITLE
skip callback

### ISSUE THREAD

**Issue by benebrice** [palkan/active_delivery#29]
## Is your feature request related to a problem? Please describe.

If you want to avoid a callback for a specific method, `skip` is not implemented

## Describe the solution you'd like

Something like [AbstractController::Callbacks](https://github.com/rails/rails/blob/6-1-stable/actionpack/lib/abstract_controller/callbacks.rb#L202-L221)

## Describe alternatives you've considered

Currently, the only solution to do that is to redefine the callback on the child class and use `except`.

**Comment by palkan** [comment]
Thanks for the suggestion!

Will add in the next release.
