### ISSUE TITLE
Side effects of upgrade to Ruby 2.7 and Rails 7 with have_delivered_to and a_hash_including

### ISSUE THREAD

**Issue by benebrice** [palkan/active_delivery#33]
## What did you do?
Upgrade from `0.4.4` to `1.0.0` 

## What did you expect to happen?
Nothing breaking

## What actually happened?
Failure on specs for `have_delivered_to` used with `a_hash_including`

## Additional context

```ruby
expect { subject.do_something }
        .to have_delivered_to(V1::SomeDelivery, :do_something).with(
          a_hash_including(foo: :bar)
        )
```

> Error raised:
>
> expected to deliver :do_something notification via V1::SomeDelivery with:
>   - params: a stash including {:foo => :bar}
>   - args: < none >
>
> exactly once, but delivered the following unexpected notifications:
>   - params: {:foo => :bar}
>   - args: []
>   - kwargs: {}

## Environment

**Ruby Version:** 2.7.2

**Framework Version (Rails, whatever):** 6.1.7.6

**Active Delivery Version:** 1.0.0

**Comment by benebrice** [comment]
🤦🏻 It was due to delivery class matching. Inheritance does not working anymore but it's not a big deal.

**Comment by palkan** [comment]
> Inheritance does not working anymore but it's not a big deal.

Oh, you're right we used `===` for a delivery instance before, now we compare classes. I'm not sure if should bring the old behaviour back and support inheritance; from the test perspective, being explicit makes more sense to me.
