### ISSUE TITLE
Syntax error: Anonymous arguments don't support in Ruby 3.1

### ISSUE THREAD

**Issue by yhirano55** [palkan/active_delivery#36]
## What did you do?

Because Anonymous args supports since Ruby 3.2, syntax error occur in Ruby 3.1.

https://github.com/palkan/active_delivery/blob/147c4763ff3be2046e365f32ccea33ed75d6c242/lib/abstract_notifier/base.rb#L28

https://rubyreferences.github.io/rubychanges/3.2.html#anonymous-arguments-passing-improvements

## What did you expect to happen?

N/A

## What actually happened?

N/A

## Additional context

N/A

## Environment

**Ruby Version:**

3.1

**Framework Version (Rails, whatever):**

N/A

**Active Delivery Version:**

1.2.0

**Comment by palkan** [comment]
Could please provide more details on your setup? Precisely, how do you require the gem?

The `active_delivery/lib/abstract_notifier/base.rb` shouldn't be loaded in Ruby 3.1, a transpiled version must be loaded instead (`active_delivery/lib/.rbnext/3.2/abstract_notifier/base.rb`). Looks like the `$LOAD_PATH` hasn't been configured properly (it's set up when you `require "active_delivery"`))

**Comment by yhirano55** [comment]
Sorry...When it bundles abstract_notifier gem which was deprecated with active_delivery gem, it happened. But it removed abstract_notifier, then it resolved.
