### ISSUE TITLE
missing keywords: :params, :sync

### ISSUE THREAD

**Issue by NikhilIluri** [palkan/active_delivery#38]
## What did you do?
Trying to upgrade my ruby version from 2.7.5 to 3.3.5,I am facing the issue missing keywords: :params, :sync, when trying to call .notify!, I am not able to find proper documentation regarding this.

## What did you expect to happen? 
Expect it to work normally.

## Environment

**Ruby Version: 3.3.5**

**Framework Version (Rails, whatever): 6.1.7**

**Active Delivery Version: 0.2.0**

**Comment by palkan** [comment]
> Active Delivery Version: 0.2.0

You should upgrade to the latest version (
"~> 1.0"); that should fix the issue.

**Comment by NikhilIluri** [comment]
Thanks, updating this and changing the syntax worked.
